# Generated by Django 4.1.7 on 2023-02-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
        ('status', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_attendant', models.CharField(max_length=30)),
                ('responsible_helper', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_payment', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('will_carried_at', models.DateTimeField()),
                ('service', models.ManyToManyField(help_text='Selecione o tipo de serviço', to='services.service')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.status')),
            ],
        ),
    ]
