# Generated by Django 4.1.7 on 2023-02-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendants', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
        ('status', '0002_alter_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_helper', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_payment', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('will_carried_at', models.DateTimeField()),
                ('attendant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendants.attendant')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('service_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('status_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.status')),
            ],
        ),
    ]
