# Generated by Django 4.1.7 on 2023-02-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
