# Generated by Django 4.1.7 on 2023-02-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_status_id'),
        ('customer_service', '0002_rename_status_customerservice_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='status_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.status'),
        ),
    ]
