# Generated by Django 4.1.7 on 2023-02-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('customer_service', '0003_alter_customerservice_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='service',
        ),
        migrations.AddField(
            model_name='customerservice',
            name='service_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
