# Generated by Django 4.1.7 on 2023-02-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('customer_service', '0004_remove_customerservice_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
    ]
