# Generated by Django 4.1.7 on 2023-02-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='isAvailable',
            new_name='isAvaliable',
        ),
    ]
