# Generated by Django 4.1.7 on 2023-02-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cellphone', models.CharField(max_length=12)),
                ('adress', models.CharField(max_length=30)),
            ],
        ),
    ]
